#see http://www.patricksoftwareblog.com/setting-up-gitlab-ci-for-a-python-application/
image: "python:3.6"

before_script:
  - python --version
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install mypy
  - pip3 install flake8
  - pip3 install pylint
  - pip3 install pytest

stages:
  - Static Analysis
  - Test

mypy:
  stage: Static Analysis
  script:
  - pwd
  - ls -l
  - MYPATH=/usr/local/lib/python3.6/site-packages
  - python -m mypy *.py
  tags:
  - vm

flake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=120 *.py
  tags:
  - vm
  
pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pylint -d C0301 *.py
  tags:
  - vm

unit_test:
  stage: Test
  script:
  - pwd
  - ls -l
  - export PYTHONPATH="$PYTHONPATH:."
  - python -c "import sys;print(sys.path)"
  - pytest
  tags:
    - vm
#most pylint errors can be fixed with 
#autopep8 --in-place --aggressive --aggressive filename.py