stages:
  - Static Analysis
  - build_env
  - push
  - Test
  - mirror
include:
  - project: 'ncmir/buildchain'
    ref: master
    file: 'cdeep3m/code-quality.gitlab-ci-template.yml'
    tags:
      - build_discworld
  - project: 'ncmir/buildchain'
    ref: master
    file: 'cdeep3m/test.gitlab-ci-template.yml'
    tags:
      - build_discworld

github_mirror:
  stage: mirror
  image:
    name: alpine/git
    entrypoint: [ "/bin/sh", "-c" ]
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  script: |
    cd /tmp
    git clone --mirror ${CI_REPOSITORY_URL} project
    cd project
    git remote add github https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/CRBS/cdeep3m2.git
    git push --mirror github
  tags:
  - build_discworld