stages:
  - Static Analysis
  - build_env
  - push
  - test

include:
  - project: 'ncmir/buildchain'
    ref: master
    file: 'cdeep3m/code-quality.gitlab-ci-template.yml'
    tags:
      - vm
  - project: 'ncmir/buildchain'
    ref: master
    file: 
      - 'cdeep3m/build_docker_env.gitlab-ci-template.yml'
    tags:
      - docker_build_borg
  - project: 'ncmir/buildchain'
    ref: master
    file: 
      - 'cdeep3m/Makefile.config'
    tags:
      - docker_build_borg
  - project: 'ncmir/buildchain'
    ref: master
    file: 
      - 'cdeep3m/Dockerfile.env'
    tags:
      - docker_build_borg