stages:
  - Static Analysis
  - build_env
  - push
  - test

include:
  - project: 'ncmir/buildchain'
    ref: master
    file: 'cdeep3m/code-quality.gitlab-ci-template.yml'
    tags:
      - vm
  - project: 'ncmir/buildchain'
    ref: master
    file: 'cdeep3m/test.gitlab-ci-template.yml'
    tags:
      - vm
include:
  - project: 'ncmir/test_repo'
    ref: master
    file: '.gitlab-ci.yml'
    tags:
      - docker_build_borg
